name: travelassistdemo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - numpy=1.23.3
  - pandas=1.5.0
  - pip:
    - requests==2.28.1
    - streamlit==1.24.0
    - unstructured==0.10.16
    - langchain==0.0.312
    - psycopg2-binary==2.9.6
    - boto3==1.28.62
    - transformers==4.34.0
    - psycopg2-binary==2.9.6
    - streamlit-chat==0.1.1
    - faiss-cpu